Quick update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -28,21 +28,23 @@ build_and_push:
         exit 1
       fi
 
-  script:
-    - echo "Tentukan versi image dengan format waktu yang lebih mudah dibaca"
-    - BUILD_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
-    - VERSION="build-$BUILD_TIMESTAMP"
-    - echo "Building Docker image version: $VERSION"
-    - echo "Siapkan QEMU untuk build multi-arch jika belum tersedia"
-    - docker buildx ls || docker run --rm --privileged tonistiigi/binfmt:latest --install all
-    - echo "Konfigurasi Docker Buildx"
-    - docker buildx use || docker buildx create --use
-    - docker buildx inspect --bootstrap
-    - echo "Build dan push multi-arch image"
-    - docker buildx build \
-        --platform $DOCKER_PLATFORM \
-        --push \
-        --no-cache \
-        --tag $DOCKER_IMAGE:$VERSION \
-        --tag $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
-        . || { echo "Docker build or push failed"; exit 1; }
+script:
+  - |
+    BUILD_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
+    VERSION="build-$BUILD_TIMESTAMP"
+  - |
+    echo "Building Docker image version: ${VERSION}"
+  - |
+    docker buildx ls || docker run --rm --privileged tonistiigi/binfmt:latest --install all
+  - |
+    docker buildx use || docker buildx create --use
+  - |
+    docker buildx inspect --bootstrap
+  - |
+    docker buildx build \
+      --platform $DOCKER_PLATFORM \
+      --push \
+      --no-cache \
+      --tag $DOCKER_IMAGE:$VERSION \
+      --tag $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
+      . || { echo "Docker build or push failed"; exit 1; }
